title: Other
author:
  name: Yoann Pigné
  email: yoann.pigne@univ-lehavre.fr

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://other.pigne.org" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-remote-theme
  - jemoji
  - jekyll-sitemap

## remote theme 
remote_theme: chesterhow/tale
permalink:    /:year-:month-:day/:title
paginate:     5


# Build settings
markdown: kramdown


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
